Add files via upload
jlmelville/funconstrain pull request #1
Opened 2022-05-19 00:55 UTC by nashjc

These have the hessian code

2022-05-19 03:46 UTC, jlmelville commented
Thank you for the PR @nashjc! Couple of initial questions:

1. Can you add yourself to the `DESCRIPTION` as a contributor?
2. Several of the Hessian functions have `error` mentioned in the comments. How concerning is that? Is it just for a specific evaluation point? Is it something that could be added to the documentation of the functions?

2022-05-19 13:43 UTC, nashjc commented
DESCRIPTION: Added ctb field. Hope I've done it right.

Removed working note crud.

2022-05-19 13:44 UTC, nashjc commented
Hope it's OK, JN

2022-05-20 03:55 UTC, jlmelville commented on R/08_bard.R
> +             h[1:n, 1,] <- .Machine$double.xmax
`n` is not defined

2022-05-20 03:56 UTC, jlmelville commented on R/08_bard.R
> +             return
What is intended here? `return(h)`? How is `flag` communicated to the caller? Getting flashbacks to my Fortran77 days here :)

2022-05-20 03:57 UTC, jlmelville commented on R/15_kow_osb.R
> +             return
Similar issue here (also `nro4` isn't defined).

2022-05-20 03:59 UTC, jlmelville commented on R/26_trigon.R
> +    m = length(par),
Unfortunately `par` is not defined at this point.

2022-05-20 04:00 UTC, jlmelville commented on R/25_var_dim.R
> +    m = length(par) + 1,
same problem here with as in `trigon`: `par` is not defined yet.

2022-05-20 04:00 UTC, jlmelville commented on R/10_meyer.R
> +          return
another `return` issue.

2022-05-20 04:04 UTC, jlmelville requested changes
First of all, this is a massive amount of very difficult work which I was unable to find the fortitude to even begin to attempt, so I really appreciate the immense effort which must have gone into this.

There are a few places where there are undefined variables and some syntax that I think needs some conversion (e.g. around `return`), but it's only very minor stuff. Would you mind taking a look and making those changes?

If you have `devtools` installed then `devtools::check()` should flag up these kinds of issues (or ctrl-shift-E after suitably configuring RStudio).

2022-05-20 13:29 UTC, nashjc commented
@jlmelville commented on this pull request.

In R/08_bard.R:

> +
+         s1 <- d2*x2 + d3*x3
+         if ( s1 != 0.0 ) {
+             t1 <- y8[i] - ( x1 + ( d1 / s1 ) )
+             t2 <- d1 / s1 ^ 2
+             t3 <- - 2.0*d1 / s1 ^ 3
+             s2 <- t1*t3 + t2 ^ 2
+             h[1,1] <- h[1,1] + 2.0
+             h[1,2] <- h[1,2] - 2.0*d2*t2
+             h[2,2] <- h[2,2] + 2.0*s2*d2 ^ 2
+             h[1,3] <- h[1,3] - 2.0*t2*d3
+             h[2,3] <- h[2,3] + 2.0*s2*d2*d3
+             h[3,3] <- h[3,3] + 2.0*s2*d3 ^ 2
+             
+         } else {
+             h[1:n, 1,] <- .Machine$double.xmax

n is not defined

JN: Now defined in code.

---------------------------------------------------------------
@jlmelville commented on this pull request.

In R/08_bard.R:

> +             flag <- - 3
+             return

What is intended here? return(h)? How is flag communicated to the caller? Getting flashbacks to my Fortran77 days here :)

JN: leftovers from the Fortran code of mgh. Commented out

---------------------------------------------------------------

@jlmelville commented on this pull request.

In R/15_kow_osb.R:

> +             h<-matrix(.Machine$double.eps, nro4, ncol=4)
+             flag <- - 3
+             return

Similar issue here (also nro4 isn't defined).

JN: commented out flag. 
    nro4 ->  nrow=4
   (typo)
---------------------------------------------------------------
@jlmelville commented on this pull request.

In R/26_trigon.R:

> @@ -56,6 +58,7 @@
 #' @export
 trigon <- function() {
   list(
+    m = length(par),

Unfortunately par is not defined at this point.

JN: replaced
    m = 30

---------------------------------------------------------------
@jlmelville commented on this pull request.

In R/25_var_dim.R:

> @@ -47,6 +49,7 @@
 #' @export
 var_dim <- function() {
   list(
+    m = length(par) + 1,

same problem here with as in trigon: par is not defined yet.

JN: removed. Wasn't needed.
---------------------------------------------------------------
@jlmelville commented on this pull request.

In R/10_meyer.R:

> +          h <- matrix(0.0, ncol=3, nrow=3)
+          flag <- - 3
+          return

another return issue.

JN: there were three returns needing "()" added.
    flag commented
---------------------------------------------------------------

2022-05-21 07:20 UTC, jlmelville commented
@nashjc was this closed by accident? I was about to say it looked good to me and merge it. Let me know if it's good to go.

2022-05-21 07:20 UTC, jlmelville approved these changes

2022-06-02 03:53 UTC, merged

2022-06-03 16:09 UTC, jlmelville commented
Many thanks for this @nashjc! This should all be merged into the `master` branch now.